CREATE DATABASE IF NOT EXISTS PhotoWall;
USE PhotoWall;
CREATE TABLE Reviews (
  id INT NOT NULL AUTO_INCREMENT,
  text TEXT,
  PRIMARY KEY (id)
);
CREATE TABLE Photos (
  id INT NOT NULL AUTO_INCREMENT,
  review_id INT NOT NULL,
  url TEXT,
  foods TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (review_id) REFERENCES Reviews(id)
);
